questions = [
    {
        "question": "Opieka zdrowotna to prawo każdego człowieka.",
        "effect": {
            "econ1": 5,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Ziemia nie powinna być obiektem do kupna i sprzedaży",
        "effect": {
            "econ1": 15,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Państwo powinno walczyć z powstawaniem monopoli.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Konieczne jest, aby rząd ingerował w gospodarkę w celu ochrony konsumentów.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Wewnętrzne sprzeczności kaptializmu są tak duże że system ten wkrótce upadnie.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rosnące nierówności są jednym z największych zagrożeń dla świata.",
        "effect": {
            "econ1": 10,
            "econ2": 5,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Mieszkanie jest przyrodzonym prawem człowieka, a nie towarem.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Pracodawca nie jest wrogiem pracownika. Wrogiem jest inny pracownik stanowiący konkurencję na rynku pracy.",
        "effect": {
            "econ1": -10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo powinno zapewniać wszystkim artykuły wymagane do przetrwania jak np. jedzenie czy wodę.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Na służbę zdrowia popyt jest nieograniczony, dlatego niebezpieczne jest to zostawiać rynkowi.",
        "effect": {
            "econ1": 5,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Nikt, nawet niepełnosprawni, nie powinni oczekiwać pomocy od państwa.",
        "effect": {
            "econ1": -5,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "W państwie powinna być stosowana jednolita forma płatności.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Brak gospodarki wolnorynkowej nieuchronnie doprowadzi do ograniczenia praw osobistych.",
        "effect": {
            "econ1": -10,
            "econ2": -10,
            "econ3": -10,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nacjonalizacja banków jest dobrym rozwiązaniem.",
        "effect": {
            "econ1": 10,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Od każdego według możliwości, dla każdego według potrzeb.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Środki produkcji powinny kolektywnie należeć do pracowników, którzy ich używają.",
        "effect": {
            "econ1": 15,
            "econ2": 5,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo powinno zapewnić obywatelom stały dochód niezależnie od ich wydajności pracy",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Socjalizm bez wolności to niewola i brutalność. Wolność bez socjalizmu to system przywilejów i niesprawiedliwość",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nierówne relacje między właścicielami firm i ich pracownikami z natury stanowią wyzysk",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Emerytura to prywatna kwestia każdego obywatela i państwo nie powinno w to ingerować",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "W społeczeństwie istnieje nierozwiązywalny konflikt klas w którym zawsze jedna będzie dominować drugą.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Austriacka szkoła ekonomii używająca inną metodologię niż inne szkoły ekonomiczne w ogóle nie powinna być uznawana za naukę",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Dziedziczenie jest uzasadnioną przyczyną bogactwa",
        "effect": {
            "econ1": -10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Majątki nie powinny być opodatkowane",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Bank centralny nie powinien istnieć",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Wysokości mandatów powinny być uzależnione od zarobków.",
        "effect": {
            "econ1": 5,
            "econ2": 5,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Cła są dobrym sposobem, aby chronić miejsca pracy w moim kraju.",
        "effect": {
            "econ1": 0,
            "econ2": 5,
            "econ3": 10,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Korzyści z wolnego handlu są większe niż szkody.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": -10,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Imigranci ekonomiczni są korzystni dla gospodarki.",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": -10,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rząd powinien chronić krajowych przedsiębiorców przed zagraniczną konkurencją.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 10,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	    {
        "question": "Własna waluta to podstawa suwerenności naszego kraju.",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Rząd powinien zwalczać różnice w płacach kobiet i mężczyzn.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Podatki to kradzież i nigdy nie jest usprawiedliwiona",
        "effect": {
            "econ1": 15,
            "econ2": 15,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Licencje, zezwolenia i związki zawodowe są niepotrzebnymi przeszkodami w prowadzeniu działalności gospodarczej",
        "effect": {
            "econ1": -5,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Publicznie finansowane badania naukowe są lepsze od tych prowadzonych przez prywatne instytucje",
        "effect": {
            "econ1": 10,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Bezrobocie jest skutkiem niewystarczającego popytu.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Co korzystne dla dobrze prosperujących przedsiębiorstw, jest w efekcie korzystne dla nas wszystkich.",
        "effect": {
            "econ1": -10,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Każdy ma prawo dysponować swoim majątkiem jak chce, więc gry hazardowe powinny być legalne.",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Należy zakazać szerzenia publicznie radykalnych, szkodliwych ideologii",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "O symbolach religijnych w szkołach i urzędach powinien decydować dyrektor lub właściciel.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 5,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Stosowanie mowy nienawiści powinno być karane",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Obraza uczuć religijnych powinna być penalizowana",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Jeżeli małżeństwa państwowe istnieją, to powinny być dostępne dla par homoseksualnych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Pary LGBT powinny mieć równe prawa, razem z adopcja dzieci.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Marihuana powinna być legalna.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Docelowo zalegalizowany powinien zostać każdy narkotyk",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Należy znieść recepty i pozwolić społeczeństwu kupować co chcą",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Małżeństwa państwowe nie powinny istnieć.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 5,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Każdy powinien mieć prawo do posiadania broni.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rząd powinien mieć większe prawo do ingerencji w życie obywateli.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Moje ciało, moja sprawa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Ochrona przed terroryzmem poszła za daleko.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": -5,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Inwigilacja obywateli jest konieczna.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Chcącemu nie dzieje się krzywda.",
        "effect": {
            "econ1": 0,
            "econ2": -5,
            "econ3": 0,
            "law1": 20,
            "law2": 0,
            "law3": 10,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rząd jest zagrożeniem dla wolności.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo powinno odpowiadać jedynie za ochronę praw jednostki",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Autorytety są korzystne dla społeczeństwa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	{
	        "question": "Instytucja policji jest źródłem nieuzasadnionej opresji obywateli dlatego powinna ona zostać gruntownie zreformowana lub zniesiona",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Każdy autorytet powinien być kwestionowany.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 5,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Szkoły nie powinny wymagać obowiązkowej obecności na lekcjach.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 5,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Ludzie z wadami dziedzicznymi nie powinni mieć prawa do posiadania potomstwa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Ważne jest, by dzieci uczyły się akceptowania dyscypliny.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Powinien istnieć ustalony, nienaruszalny program dla wszystkich szkół",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Studia powinny być finansowane przez państwo.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo powinno zakazać takie kierunki jak gender studies.",
        "effect": {
            "econ1": 0,
            "econ2": 5,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Jeżeli już istnieją uniwersytety państwowe to powinny być autonomiczne",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Ci, którzy krytykują rząd powinni zostać usunięci z kraju.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": -5,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Policja powinna mieć więcej władzy oraz ochrony.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": -5,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "To ważne, żeby utrzymywać prawo i porządek.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": -10,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rząd nie ma żadnego interesu w zaglądaniu do życia prywatnego większości ludzi.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Policja powinna być bardziej regulowana.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Nie powinno być autorytetów bezspornych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Wolność ludzi powinna nie mieć granic.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Demokracja to de facto tyrania większości nad mniejszością, co jest jej istotną wadą",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo funkcjonowałoby lepiej gdyby jedna osoba sprawowała władze.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "System jednopartyjny jest korzystny.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Gdyby wybory zmieniały cokolwiek, to politycy dawno by je zdelegalizowali",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Wielkim plusem jednopartyjnego systemu jest brak dyskusji opóźniających postęp w systemach demokratycznych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Demokracja bezpośrednia jest najlepszą formą rządów.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Ludzie sami powinni głosować nad każdym problemem.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 10,
            "law3": 5,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "To ważne, by rząd postępował zgodnie z opinią większości, nawet jeśli jest błędna.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Im więcej ludzi jest pytanych, tym większa szansa na podjęcie najlepszej decyzji.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Każda osoba powinna posiadać jeden głos, który jest równy wobec głosów innych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Większość populacji podejmuje złe decyzje.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Naród musi bezwarunkowo słuchać przywództwa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Moralność jest subiektywna.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 5,
            "society2": 0,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nawet jeżeli istnieje moralność obiektywna człowiek nie może jej poznać.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nawet jeżeli istnieje moralność obiektywna człowiek nie może jej poznać",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Dobro jednostki jest ważniejsze od dobra ogółu.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Ostatecznie jesteśmy nieistotni jako jednostki, tylko nasze wysiłki na rzecz grupy mają trwały efekt.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Powinniśmy skupić się na jednostkach, a nie na tożsamościach grupowych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Żyj i pozwól żyć to najlepsza filozofia życiowa.",
        "effect": {
            "econ1": 0,
            "econ2": -5,
            "econ3": 0,
            "law1": 10,
            "law2": 0,
            "law3": 10,
            "law4": 5,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Każdy styl życia wpływa w jakiś sposób na społeczeństwo i powinien być odpowiednio potępiony lub zatwierdzony.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Ograniczenie praw jednostki jest w porządku, jeśli społeczność na tym skorzysta.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nie mamy prawa ingerować militarnie w innych państwach.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 10,
            "society1": -5,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Ważniejsze jest utrzymać pokojowe relacje niż rozwijać naszą siłę.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Powinna być obowiązkowa służba wojskowa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Tylko ci, którzy służyli w wojsku powinni być uprawnieni do posiadania wpływu na to, kto jest u władzy.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": -10,
            "law3": 0,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Wojna jest konieczna, żeby ekonomia dobrze się rozwijała.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -5,
            "society2": 0,
            "society3": 0,
            "society4": -5,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Dyplomacja tylko szkodzi państwom.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 5,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Sojusze są ważne, żeby chronić państwo.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 10,
            "society1": 10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "ONZ lub NATO powinno zaprowadzić demokracje w krajach niedemokratycznych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": 5,
            "law3": 0,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 10,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Powinnismy rozwijać własne wojsko, zamiast skupiać się na sojuszach.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Silne wojsko daje nam wyższą pozycję wśród narodów",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo powinno dążyć do uzyskania utraconych na przestrzeni lat ziem",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -15,
            "society1": -15,
            "society2": -5,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Wszystko w państwie, nic poza państwem, nic przeciw państwu",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": -10,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
    {
	        "question": "Nikt nie wybiera swojego kraju urodzenia, więc nie ma powodów do dumy z tego.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 5,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Jednolitość rasowa korzystnie wpływa na społeczeństwo",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Mniejszosci etniczne trudniej asymilują się z naszą kulturą, więc powinno ich być jak najmniej.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Unia Europejska powinna mieć mniejszy wpływ na państwa członkowskie.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Państwo nie powinno przyjmować uchodźców z krajów obcych kulturowo.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "UE powinna być jednym superpaństwem.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
    {
        "question": "Ważne jest zachowanie suwerenności naszego kraju.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "ONZ nie powinna istnieć",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Zawsze będę stał po stronie mojego kraju niezależnie czy ma rację.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Zjednoczony rząd światowy byłby korzystny dla ludzkości",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
    {
	        "question": "Moje państwo powinno trzymać się z dala od relacji międzynarodowych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Pomoc międzynarodowa to strata pieniędzy.",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": -10,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Nie powinno być praw międzynarodowych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Kobiety mają równe prawa, więc protesty feministek nie mają sensu.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Aborcja to morderstwo.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	    {
        "question": "Różnice w rolach płciowych mogą być wytłumaczone biologią.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Klauzula sumienia powinna zostać zniesiona",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Matki mogą robić karierę, ale ich głównym obowiązkiem jest zajmowanie się domem.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Tradycja po prostu przeszkadza w postępie technologicznym.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Gonić postęp za każdą cenę jest niebezpieczne.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 5,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Starsi w społeczeństwie znają dla niego najlepszą drogę.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Internet powinien zostać zakazany.",
        "effect": {
            "econ1": 0,
            "econ2": 5,
            "econ3": 0,
            "law1": -10,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Społeczeństwo powinno kultywować dawne tradycje.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": -5,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Tradycja jest ważna w spajaniu narodu.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": -5,
            "society2": -10,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Kościół powinien zostać opodatkowany.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Nie można być moralnym bedąc innej religii niż moja.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": -10,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": -10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Rząd nie powinien finansować żadnych organizacji religijnych w żaden sposób.",
        "effect": {
            "econ1": 0,
            "econ2": -10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Każda religia musi być postrzegana równo przez rząd.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Musi istnieć rozdział pomiędzy kościołem i państwem.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Dzieci powinny być edukowane w wartościach religijych.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -10,
            "society3": -10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Moje wartości religijne powinny być rozprzestrzenione tak bardzo, jak możliwe.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -5,
            "society1": 0,
            "society2": -10,
            "society3": -10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Większość złych rzeczy zdarzających się na świecie jest spowodowana przez nasze oddalanie się od religii.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -5,
            "society3": -10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Rząd ma prawo uprzywilejować jedną religię.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": -5,
            "law2": -5,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": -5,
            "society3": -10,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "W obliczu obecnego zagrożenia klimatycznego koniecznie dla ludzkości jest znaczące ograniczenie produkcji i spożycia mięsa",
        "effect": {
            "econ1": 0,
            "econ2": 5,
            "econ3": 0,
            "law1": -5,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
	        "question": "Należy walczyć z globalnym ociepleniem.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Należy zakazać wydobycia węgla.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Nasza energia powinna pochodzić z odnawialnych źródeł energii.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Gdyby pojawiła się możliwość czerpania energii z fuzji jądrowych byłoby to preferowane przeze mnie źródło energii.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Człowiek przywiązuje obecnie zbyt dużą wagę do ochrony środowiska.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": -10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Powinny istnieć surowe prawa związane z ekologią i emisją CO2 i gazów cieplarnianych",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Państwo powinno dofinansowywać zakup przedmiotów pro-ekologicznych w celu zachęcenia do walki z globalnym ociepleniem.",
        "effect": {
            "econ1": 10,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Zwierzęta powinny mieć takie same prawa co ludzie",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 10,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Hodowla zwierząt na futro powinna być zakazana.",
        "effect": {
            "econ1": 0,
            "econ2": 10,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 10,
            "society3": 0,
            "society4": 5,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Cel uświęca środki.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 15,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Rewolucja to najlepszy sposób na osiągnięcie idealnego społeczeństwa.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 10,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Negatywne konsekwencje rewolucji przeważają na ogół nad korzyściami.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": -10,
            "state2": 0,
            "state3": 0,
        }
    },
    {
        "question": "Rewolucyjna przemoc jest dopuszczalna, o ile końcowy wynik jest pozytywny.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 10,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
        "question": "Narody uciskane mają prawo wziąć udział w gwałtownym powstaniu, gdy wszystkie inne możliwości zostały wyczerpane.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 10,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Oko za oko uczyni cały świat ślepym.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 0,
        }
    },
	    {
	        "question": "Ważniejsza od odbycia kary jest resocjalizacja.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 10,
            "state3": 0,
        }
    },
	    {
	        "question": "Więźniowie powinni pracować na swoje utrzymanie podczas odbywania wyroku.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 5,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": -10,
            "state3": 0,
        }
    },
	    {
	        "question": "Kara śmierci powinna być stosowana za najgorsze wykroczenia.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": -10,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": -10,
            "state3": 0,
        }
    },
	    {
	        "question": "Stratą czasu jest próba resocjalizacji niektórych przestępców.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": -10,
            "state3": 0,
        }
    },
	    {
	        "question": "Prawa stanowe oraz lokalne powinny mieć pierwszeństwo nad prawami narodowymi.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 10,
        }
    },
	    {
	        "question": "Ogólnokrajowy rząd nie jest w stanie zrozumieć, czego ludzie potrzebują.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 10,
        }
    },
	    {
        "question": "Ludzie powinni uważać się za obywateli swojego kraju, a nie stanu.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
    {
        "question": "Władze lokalne powinny posiadać więcej uprawnień, niż obecnie.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 10,
        }
    },
	    {
        "question": "Prawa powinny się różnić w zależności od regionu oraz kultury w granicach kraju.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 10,
        }
    },
	    {
	        "question": "Władze lokalne zajmują się problemami, którymi rząd ogólnokrajowy bez ich pomocy nigdy by się nie zainteresował.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": 10,
        }
    },
	    {
	        "question": "Kraj nie może funkcjonować bez ogólnokrajowego rządu.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
	    {
	        "question": "Jest wiele problemów, których nie ma sensu zawierzać władzom lokalnym.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
	    {
	        "question": "Rząd ogólnokrajowy musi być silny, żeby adekwatnie chronić wszystkich swoich obywateli.",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": -10,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    },
	    {
	        "question": "Silne władze stanowe osłabiają kraj",
        "effect": {
            "econ1": 0,
            "econ2": 0,
            "econ3": 0,
            "law1": 0,
            "law2": 0,
            "law3": 0,
            "law4": 0,
            "society1": 0,
            "society2": 0,
            "society3": 0,
            "society4": 0,
            "state1": 0,
            "state2": 0,
            "state3": -10,
        }
    }
];
